## Preliminaries

In [24]:
# initialization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
import pickle
import time
import threading

import torch
import transformers

from torch import nn
from typing import Dict, Iterable, Callable
from torch import optim

from torch.utils.tensorboard import SummaryWriter
from transformers import RobertaModel, RobertaTokenizer

from datasets import load_dataset
import pickle
import os


## Exploration 1

In [11]:
from transformers import pipeline
classifier = pipeline('zero-shot-classification', model="facebook/bart-large-mnli")


candidate_labels = vocabulary


config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

{'sequence': 'The product of the moving force and mass of an object is equal to the acceleration of the object.',
 'labels': ['global_facts',
  'conceptual_physics',
  'college_physics',
  'moral_scenarios',
  'elementary_mathematics',
  'public_relations',
  'college_mathematics',
  'security_studies',
  'econometrics',
  'abstract_algebra',
  'formal_logic',
  'clinical_knowledge',
  'logical_fallacies',
  'professional_law',
  'high_school_physics',
  'machine_learning',
  'college_computer_science',
  'college_biology',
  'electrical_engineering',
  'professional_accounting',
  'management',
  'computer_security',
  'moral_disputes',
  'college_chemistry',
  'professional_psychology',
  'us_foreign_policy',
  'miscellaneous',
  'medical_genetics',
  'professional_medicine',
  'high_school_macroeconomics',
  'high_school_microeconomics',
  'high_school_us_history',
  'business_ethics',
  'international_law',
  'jurisprudence',
  'high_school_statistics',
  'high_school_mathematics',

In [19]:
seq = "The product of the moving force and mass of an object is equal to the acceleration of the object."
out = classifier(seq, candidate_labels)
sorted( zip(out['labels'], out['scores']), key = lambda x : -x[1])[:10]

[('global_facts', 0.07534562051296234),
 ('conceptual_physics', 0.04785466939210892),
 ('college_physics', 0.04717550426721573),
 ('moral_scenarios', 0.03178830444812775),
 ('elementary_mathematics', 0.028261151164770126),
 ('public_relations', 0.027446452528238297),
 ('college_mathematics', 0.025162814185023308),
 ('security_studies', 0.02490970678627491),
 ('econometrics', 0.024074561893939972),
 ('abstract_algebra', 0.02260439097881317)]

In [126]:
seq = "How many chromosomes do all human somatic cells contain?'"
out = classifier(seq, candidate_labels)
sorted( zip(out['labels'], out['scores']), key = lambda x : -x[1])[:10]

[('global_facts', 0.10554464161396027),
 ('medical_genetics', 0.0645785704255104),
 ('clinical_knowledge', 0.06147882714867592),
 ('anatomy', 0.04594443738460541),
 ('human_sexuality', 0.0392792671918869),
 ('elementary_mathematics', 0.03646574914455414),
 ('college_biology', 0.02971418760716915),
 ('conceptual_physics', 0.02682461403310299),
 ('human_aging', 0.026544885709881783),
 ('college_physics', 0.026392778381705284)]

## Exploration 2

In [21]:
!pip install setfit

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 KB 1.3 MB/s eta 0:00:002.1 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 20.2 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 KB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 KB 18.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 2.6 MB/s eta 0:00:00m eta 0:00:010:00:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 KB 3.5 MB/s eta 0:00:00 MB/s eta 0:00:01:01


In [22]:
from datasets import load_dataset
from sentence_transformers.losses import CosineSimilarityLoss

from setfit import SetFitModel, SetFitTrainer


In [100]:
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")

config.json:   0%|          | 0.00/594 [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.73k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.


In [25]:
DATAPATH = '/home/igli/Downloads/data/dev'
vocabulary = [os.path.splitext(x)[0][:-4] for x in os.listdir(DATAPATH)]

In [135]:
from datasets import Dataset
import random

def make_dataset(datapath, subdirs, few_shot = 10):
    root = datapath
    train_data = {'text' : [], 'label':[]}
    test_data  = {'text' : [], 'label':[]}
    
    for subject in vocabulary:
        texts = []
        for subdir in subdirs:
            subject_csv = subject + f"_{subdir}.csv"
            path = os.path.join(root, subdir)
            df = pd.read_csv(os.path.join(path, subject_csv), header=None, usecols=[0])
            texts += list(df[0])
            
        random.shuffle(texts)
        train_data['text'] += texts[:few_shot]
        test_data['text']  += texts[few_shot:]
        
        train_data['label'] += [subject] * few_shot
        test_data['label']  += [subject] * (len(texts)-few_shot)
        
    return Dataset.from_dict(train_data), Dataset.from_dict(test_data)

data = make_dataset('/home/igli/Downloads/data/', ['val', 'dev', 'test'], few_shot=40)
train_data = data[0]
test_data = data[1]

In [140]:
from sentence_transformers.losses import CosineSimilarityLoss

trainer = SetFitTrainer(
    model=model,
    train_dataset=train_data,
    eval_dataset=test_data,
    loss_class=CosineSimilarityLoss,
    batch_size=10,
    num_iterations=20, # Number of text pairs to generate for contrastive learning
    num_epochs=1 # Number of epochs to use for contrastive learning
)

/tmp/ipykernel_1157601/2686327976.py:3: DeprecationWarning: `SetFitTrainer` has been deprecated and will be removed in v2.0.0 of SetFit. Please use `Trainer` instead.
  trainer = SetFitTrainer(


Map:   0%|          | 0/2280 [00:00<?, ? examples/s]

In [145]:
trainer.train()
metrics = trainer.evaluate()

KeyboardInterrupt: 

In [149]:
model.save_pretrained("setfit_topic_classifier")

### Testing the model

In [146]:
torch.argsort(model.predict_proba(['The product of the moving force and mass of an object is equal to the acceleration of the object.']))

tensor([[15,  4, 14, 37,  2, 44,  0, 29, 32,  3, 19, 46, 26, 35, 42, 52, 41, 20,
         11, 18, 21,  7, 30, 54, 40, 36, 17, 51, 23, 55,  1, 47, 28, 43, 49, 38,
         24, 45, 31, 48, 39, 16, 53, 56, 33, 22, 34, 25,  6, 13,  8, 50,  5,  9,
         12, 10, 27]])

In [147]:
torch.argsort(model.predict_proba(['The product of the moving force and mass of an object is equal to the acceleration of the object.']))

tensor([[15,  4, 14, 37,  2, 44,  0, 29, 32,  3, 19, 46, 26, 35, 42, 52, 41, 20,
         11, 18, 21,  7, 30, 54, 40, 36, 17, 51, 23, 55,  1, 47, 28, 43, 49, 38,
         24, 45, 31, 48, 39, 16, 53, 56, 33, 22, 34, 25,  6, 13,  8, 50,  5,  9,
         12, 10, 27]])

In [118]:
torch.argsort(model.predict_proba(['How many chromosomes do all human somatic cells contain?']))

tensor([[50,  6, 10,  5, 13, 33, 35,  9, 26, 36, 53, 49, 41, 52, 14, 31,  3, 48,
         45, 21,  8, 37, 17, 27, 23, 16, 24,  0, 54, 42, 32, 56, 38,  7, 39, 51,
         22, 30, 25, 43, 47, 34, 19, 20, 12, 11,  2, 15, 29, 46, 55, 28, 18, 40,
          1,  4, 44]])

In [144]:
model.id2label[8]

'college_mathematics'

## Exploration 3

In [2]:
from transformers import RobertaForMaskedLM, RobertaTokenizer

# Initializing a model (with random weights) from the configuration

model = RobertaForMaskedLM.from_pretrained("FacebookAI/roberta-base")
tokenizer = RobertaTokenizer.from_pretrained("FacebookAI/roberta-base")


# Accessing the model configuration

configuration = model.config

In [14]:
inputs = tokenizer("The product of the moving force and mass of an object is equal to the acceleration of the object. The topic of this text is <mask>.", return_tensors="pt")
inputs

{'input_ids': tensor([[    0,   133,     9,     5,  1375,  1370,     8,  2862,     9,    41,
          7626,    16,  3871,     7,     5, 19308,     9,     5,  7626,     4,
            20,  5674,     9,    42,  2788,    16, 50264,     4,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]])}

In [37]:
model.__dir__()

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_assisted_decoding',
 '_auto_class',
 '_autoset_attn_implementation',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_beam_sample',
 '_beam_search',
 '_buffers',
 '_call_impl',
 '_check_and_enable_flash_attn_2',
 '_check_and_enable_sdpa',
 '_compiled_call_impl',
 '_constrained_beam_search',
 '_contrastive_search',
 '_convert_head_mask_to_5d',
 '_copy_lm_head_original_to_resized',
 '_create_repo',
 '_dispatch_accelerate_model',
 '_expand_inputs_for_generation',
 

In [20]:
tokenizer.decode([19308, 17244, 17759])

' acceleration gravity physics'

In [25]:
with torch.no_grad():
    logits = model(**inputs).logits
    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]
    predicted_token_id = torch.argsort(logits[0, mask_token_index],axis=-1,descending=True).squeeze()[:10]
    print(predicted_token_id.shape)
    print(tokenizer.decode(predicted_token_id.squeeze()))
    predicted_token_id = logits[0, mask_token_index].argmax(axis=-1)
    print(predicted_token_id)
    p = tokenizer.decode(predicted_token_id)
p

torch.Size([10])
 acceleration gravity physics inertia momentum relativity accelerating transportation motion speed
tensor([19308])


' acceleration'

## Exploration 4

In [26]:
vocabulary

['miscellaneous',
 'us_foreign_policy',
 'high_school_geography',
 'high_school_statistics',
 'high_school_computer_science',
 'international_law',
 'medical_genetics',
 'econometrics',
 'college_biology',
 'high_school_macroeconomics',
 'high_school_us_history',
 'professional_medicine',
 'moral_scenarios',
 'high_school_chemistry',
 'nutrition',
 'college_computer_science',
 'human_sexuality',
 'sociology',
 'anatomy',
 'business_ethics',
 'formal_logic',
 'college_physics',
 'college_chemistry',
 'machine_learning',
 'security_studies',
 'world_religions',
 'high_school_world_history',
 'professional_law',
 'moral_disputes',
 'public_relations',
 'astronomy',
 'college_medicine',
 'logical_fallacies',
 'jurisprudence',
 'high_school_psychology',
 'computer_security',
 'high_school_government_and_politics',
 'high_school_mathematics',
 'human_aging',
 'high_school_physics',
 'professional_psychology',
 'high_school_european_history',
 'professional_accounting',
 'management',
 'clini

In [2]:
model_id

'TheBloke/WizardCoder-Python-7B-V1.0-GGUF'

In [4]:
import transformers
import torch
import time
# model_id = "microsoft/Phi-3-mini-128k-instruct"
# model_id = "Orenguteng/Llama-3-8B-Lexi-Uncensored"
# model_id = "meta-llama/Meta-Llama-3-8B-Instruct"

model_names = ["google/gemma-7b", "mistralai/Mistral-7B-Instruct-v0.1", "deepseek-ai/deepseek-coder-6.7b-instruct", 'meta-llama/CodeLlama-7b-Instruct-hf', 'Qwen/CodeQwen1.5-7B-Chat', 'TheBloke/WizardCoder-Python-7B-V1.0-GGUF', ]
for _ in range(10000):
    for model_id in model_names:
        pipeline = transformers.pipeline(
            "text-generation",
            model=model_id,
            model_kwargs={"torch_dtype": torch.bfloat16},
            device_map="auto",
        )
    time.sleep(10)


config.json:   0%|          | 0.00/701 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/31.7k [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/3.89G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.71G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/4.46M [00:00<?, ?B/s]

ValueError: Could not load model TheBloke/WizardCoder-Python-7B-V1.0-GGUF with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>,). See the original errors:

while loading with AutoModelForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/home/igli/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 283, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/igli/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/home/igli/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3406, in from_pretrained
    raise EnvironmentError(
OSError: TheBloke/WizardCoder-Python-7B-V1.0-GGUF does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.




In [30]:
messages = [
    {"role": "system", "content": f"You are to act as a topic classifer whose labels come from the vocabulary: {vocabulary}. You only reply with three words from this list, identifying the top 3 topics of that the sentence feeded as a prompt is most likely to be related to."},
    {"role": "user", "content": "Commutator in DC generator is used for convert AC armature current in to DC."},
]

prompt = pipeline.tokenizer.apply_chat_template(
        messages, 
        tokenize=False, 
        add_generation_prompt=True
)

terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = pipeline(
    prompt,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
print(outputs[0]["generated_text"][len(prompt):])

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


high_school_electrical_engineering, college_physics, miscellaneous


## LM distillation/decoder finetuning exploration

In [39]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer_gemma7b = AutoTokenizer.from_pretrained("google/gemma-1.1-7b-it")
model_gemma7b = AutoModelForCausalLM.from_pretrained(
    "google/gemma-1.1-7b-it",
    device_map="auto",
    torch_dtype=torch.bfloat16
)

input_text = "Write me a poem about Machine Learning."
input_ids = tokenizer_gemma7b(input_text, return_tensors="pt").to("cuda")

outputs = model_gemma7b.generate(**input_ids)
print(tokenizer_gemma7b.decode(outputs[0]))

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/620 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Error while downloading from https://cdn-lfs-us-1.huggingface.co/repos/68/76/68769f4e52bc8e65ae728ac49264fbe5bd7b3ceded465055a3b5115c29a85085/c805f0861ac667165cca12e20445bf2c4e55ba665afde00cb9b355f5666724d6?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model-00002-of-00004.safetensors%3B+filename%3D%22model-00002-of-00004.safetensors%22%3B&Expires=1715431468&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxNTQzMTQ2OH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzY4Lzc2LzY4NzY5ZjRlNTJiYzhlNjVhZTcyOGFjNDkyNjRmYmU1YmQ3YjNjZWRlZDQ2NTA1NWEzYjUxMTVjMjlhODUwODUvYzgwNWYwODYxYWM2NjcxNjVjY2ExMmUyMDQ0NWJmMmM0ZTU1YmE2NjVhZmRlMDBjYjliMzU1ZjU2NjY3MjRkNj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=JaENpZWNtSnmzfxnmR0fJ5FU54gsWoFf8pySrPWBACCS4JJCbCjLDlbvG84d5I6%7E7s8D2dhmq4rEF9CWNQGN1CnFgpwl0qfBnTLNdZj9wnuPt7Khq-KErjt51QAA%7Ea2uO1vFtVdLDmoJUKv4Kn1bKZZ6iXkFwZjGVYhXdute-0uth22mPOdikcOz31PzWsDZUHPKp-Ww8

model-00002-of-00004.safetensors:  13%|#2        | 640M/4.98G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.11G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

/home/igli/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1132: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


<bos>Write me a poem about Machine Learning.

Silicon whispers, circuits glow,
Data flows in


In [40]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer_gemma2b = AutoTokenizer.from_pretrained("google/gemma-1.1-2b-it")
model_gemma2b = AutoModelForCausalLM.from_pretrained(
    "google/gemma-1.1-2b-it",
    device_map="auto",
    torch_dtype=torch.bfloat16
)

input_text = "Write me a poem about Machine Learning."
input_ids = tokenizer_gemma2b(input_text, return_tensors="pt").to("cuda")

outputs = model_gemma2b.generate(**input_ids)
print(tokenizer_gemma2b.decode(outputs[0]))


tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/618 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

<bos>Write me a poem about Machine Learning.

In circuits of logic, a mind unseen,



In [38]:
from huggingface_hub import login
login()